apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "squadron-postgresql.fullname" . }}-init
  labels:
    {{- include "squadron-postgresql.labels" . | nindent 4 }}
data:
  01-init-databases.sql: |
    {{- range .Values.initDatabases }}
    CREATE DATABASE {{ . }};
    {{- end }}
    {{- range .Values.initDatabases }}
    GRANT ALL PRIVILEGES ON DATABASE {{ . }} TO {{ $.Values.auth.username }};
    {{- end }}
