apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "squadron-keycloak.fullname" . }}
  labels:
    {{- include "squadron-keycloak.labels" . | nindent 4 }}
data:
  KC_DB: {{ .Values.database.vendor | quote }}
  KC_DB_URL: {{ .Values.database.url | quote }}
  KC_HOSTNAME_STRICT: {{ .Values.hostname.strict | quote }}
  KC_HTTP_ENABLED: "true"
  KC_PROXY_HEADERS: {{ .Values.proxy.headers | quote }}
