{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: squadron-gateway
  namespace: {{ include "squadron.namespace" . }}
  labels:
    {{- include "squadron.serviceLabels" (dict "root" . "service" "gateway") | nindent 4 }}
spec:
  type: {{ .Values.gateway.serviceType | default "LoadBalancer" }}
  ports:
    - port: {{ .Values.gateway.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "squadron.selectorLabels" (dict "root" . "service" "gateway") | nindent 4 }}
{{- end }}
