{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: squadron-services
  namespace: {{ include "squadron.namespace" . }}
  labels:
    {{- include "squadron.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: squadron
  namespaceSelector:
    matchNames:
      - {{ include "squadron.namespace" . }}
  endpoints:
    - port: http
      path: {{ .Values.monitoring.serviceMonitor.path }}
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
{{- end }}
