image:
  repository: redis
  tag: "7-alpine"
  pullPolicy: IfNotPresent

persistence:
  enabled: true
  size: 5Gi
  storageClass: ""
  accessModes:
    - ReadWriteOnce

resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

service:
  type: ClusterIP
  port: 6379

config:
  maxmemory: 256mb
  maxmemoryPolicy: allkeys-lru
  appendonly: "yes"

nodeSelector: {}
tolerations: []
affinity: {}
